# Generated by Django 6.1 on 2026-09-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('outlet', models.CharField(help_text='Publication or channel, e.g. TechCrunch', max_length=200)),
                ('beat', models.CharField(blank=True, help_text='Topic focus, e.g. fintech, climate tech', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Style, past coverage, preferences')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
